[extend]
useDefault = true

[allowlist]
description = "Global allowlist"
paths = [
  '''node_modules''',
  '''pnpm-lock\.yaml''',
  '''\.env\.local\.example''',
  '''public/.+\.(png|jpg|svg|webp|ico)''',
]
regexes = [
  '''example\.(com|supabase\.co)''',
  '''your-(anon-key|project)''',
]
