import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import sonarjs from 'eslint-plugin-sonarjs'
import unicorn from 'eslint-plugin-unicorn'
// NOTE: eslint-plugin-tailwindcss v3 only supports Tailwind v3 (it errors on v4 CSS-based config).
// This project uses Tailwind v4, so we omit the plugin and rely on `prettier-plugin-tailwindcss`
// (already wired into Prettier) for class-name ordering. Re-enable once tailwindcss v4 plugin is stable.
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import next from '@next/eslint-plugin-next'
import prettier from 'eslint-config-prettier'

export default [
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  sonarjs.configs.recommended,
  {
    plugins: {
      unicorn,
      react,
      'react-hooks': reactHooks,
      '@next/next': next,
    },
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: {
        React: 'readonly',
      },
    },
    settings: {
      react: { version: 'detect' },
    },
    rules: {
      // Next.js
      ...next.configs.recommended.rules,
      ...next.configs['core-web-vitals'].rules,

      // React
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',

      // Tailwind — handled by prettier-plugin-tailwindcss (class ordering on save / format)

      // Unicorn — selected rules
      'unicorn/filename-case': ['error', { case: 'kebabCase' }],
      'unicorn/no-null': 'off',
      'unicorn/prevent-abbreviations': 'off',
      'unicorn/no-array-reduce': 'off',

      // SonarJS — already covers cognitive complexity, duplications
      'sonarjs/cognitive-complexity': ['error', 15],
      'sonarjs/no-duplicate-string': ['error', { threshold: 4 }],

      // TypeScript strictness
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/consistent-type-imports': 'error',
    },
  },
  {
    files: ['**/*.{js,mjs,cjs}'],
    ...tseslint.configs.disableTypeChecked,
  },
  {
    files: ['tests/**/*.{ts,tsx}'],
    rules: {
      'sonarjs/no-duplicate-string': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
    },
  },
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'public/**',
      'supabase/migrations/**',
      'worker/**', // Python worker project (not TS)
      'next-env.d.ts', // auto-generated by Next.js, must not be edited
    ],
  },
  prettier, // must be last — disables ESLint rules conflicting with Prettier
]
